# Generated by Django 5.1.2 on 2024-10-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=100, verbose_name='')),
                ('date_of_meeting', models.DateField(verbose_name='')),
                ('attended', models.CharField(max_length=50)),
            ],
        ),
    ]
