# Generated by Django 5.1.2 on 2024-10-14 00:09

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Baptized', 'Baptized'), ('Confirmed', 'Confirmed'), ('Visitor', 'Visitor')], default=['Baptized'], max_length=26),
        ),
        migrations.AddField(
            model_name='attendance',
            name='meeting',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('team', 'Team Meeting'), ('client', 'Client Meeting'), ('project', 'Project Meeting')], default=['team'], max_length=19),
        ),
        migrations.AddField(
            model_name='attendance',
            name='name',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bob', 'Bob'), ('Alice', 'Alice'), ('John', 'John')], default=['Bob'], max_length=14),
        ),
        migrations.AddField(
            model_name='attendance',
            name='remarks',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attended',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('zoom', 'Zoom')], default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date_of_meeting',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='email_address',
            field=models.EmailField(max_length=100),
        ),
    ]
