# Generated by Django 5.1.2 on 2024-10-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_category_attendance_meeting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='email_address',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='remarks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
