# Generated by Django 5.1.2 on 2024-10-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_email_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendence_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
