# Generated by Django 5.1.2 on 2024-10-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_attendence_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendence_id',
            field=models.PositiveBigIntegerField(default=[1], verbose_name=''),
        ),
    ]
