# Generated by Django 5.1.2 on 2024-10-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_rename_attendence_id_attendance_attendence_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendence_number',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_number',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attended',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=5),
        ),
    ]
