# Generated by Django 5.1.2 on 2024-10-14 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_remove_attendance_attendence_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date_of_meeting',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
